### PR TITLE
fix(crosschain): extend inTxHashToCctx to accommodate multiple cctxes caused by a single inTxHash

### LINKED ISSUE #621: RPC/state variable: inTxHashToCctx should map a inTxHash to an array of Cctx to prepare for multiple outbounds
a single inTx can potentially cause multiple outbound txs (managed by multiple CCTXs). 

the state variable and RPC inTxHashToCctx should reflect that.

### PR DESCRIPTION
**Pull request by brewmaster012**
closes #621 

This PR accommodates multiple outbound CCTXs generated by a single inbound transaction (inTx)

### CODE REVIEW

File: x/crosschain/keeper/keeper_cross_chain_tx.go [hunk 1]
```diff
@@ -23,10 +23,10 @@ func (k Keeper) SetCctxAndNonceToCctxAndInTxHashToCctx(ctx sdk.Context, send typ
 	store.Set(types.KeyPrefix(send.Index), b)
 
 	// set mapping inTxHash -> cctxIndex
-	k.SetInTxHashToCctx(ctx, types.InTxHashToCctx{
-		InTxHash:  send.InboundTxParams.InboundTxObservedHash,
-		CctxIndex: send.Index,
-	})
+	in, _ := k.GetInTxHashToCctx(ctx, send.InboundTxParams.InboundTxObservedHash)
```
Comment (kingpinXD) [inline x/crosschain/keeper/keeper_cross_chain_tx.go:26]: Why not check the found flag ?

**Review by kingpinXD — APPROVED** [review]

**Review by fadeev — APPROVED** [review]
Didn't test it, but looks good.
